# Generated by Django 5.1.7 on 2025-07-03 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('repetition', models.CharField(choices=[('no', 'No recurrente'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='no', max_length=10, verbose_name='Repetición')),
                ('start_time', models.TimeField(verbose_name='Hora desde')),
                ('end_time', models.TimeField(verbose_name='Hora hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Fecha límite')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('time_window', models.CharField(blank=True, choices=[('hoy', 'Hoy'), ('semana', 'Esta semana'), ('mes', 'Este mes')], max_length=20, verbose_name='Plazo de tiempo')),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10, verbose_name='Prioridad')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Porcentaje completado', verbose_name='Progreso (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
