# Generated by Django 5.1.7 on 2025-07-05 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_window',
        ),
        migrations.AddField(
            model_name='event',
            name='related_task',
            field=models.ForeignKey(blank=True, help_text='Si se generó como sesión de enfoque para una tarea', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.task', verbose_name='Tarea relacionada'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('skipped', 'Omitido')], default='pending', help_text='Estado de este evento/session', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_scheduled',
            field=models.BooleanField(default=False, help_text='Indica si ya se generaron sesiones de enfoque', verbose_name='Auto-agendada'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Fecha en que se puede empezar la tarea', null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Deadline para completar la tarea', null=True, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje completado de la tarea', verbose_name='Progreso (%)'),
        ),
    ]
