# Generated by Django 5.1.7 on 2025-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_task_time_window_event_related_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='session_length',
            field=models.PositiveIntegerField(default=1, help_text='Horas por bloque de trabajo generado automáticamente', verbose_name='Duración de sesión (horas)'),
        ),
    ]
